-- HN Ledger — seed data (categories, UOMs, products, vendors)
-- Run: wrangler d1 execute DB --remote --file=seed-ledger.sql

-- ─── CATEGORIES ───
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (1, 'Raw Materials', '🥩', 10, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (2, 'Salaries', '💼', 20, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (3, 'Rent', '🏠', 30, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (4, 'Utilities', '💡', 40, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (5, 'Operations (Petty)', '🧹', 50, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (6, 'Maintenance & Repair', '🔧', 60, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (7, 'Marketing & Promotion', '📢', 70, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (8, 'Tech, SaaS & Banking', '💻', 80, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (9, 'Compliance & Legal', '📋', 90, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (10, 'Police & Hafta', '🚓', 100, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (11, 'Capex & Equipment', '🏗️', 110, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (12, 'Transport & Logistics', '🚚', 120, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (13, 'Owner / Family Drawings', '👨‍👩‍👧', 130, 'seed');
INSERT OR IGNORE INTO ledger_categories (id, name, emoji, sort_order, created_by) VALUES (14, 'Miscellaneous', '📦', 140, 'seed');

-- ─── UOMs ───
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('kg', 'Kilogram', 10);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('gm', 'Gram', 20);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('ltr', 'Litre', 30);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('ml', 'Millilitre', 40);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('pcs', 'Pieces', 50);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('dozen', 'Dozen', 60);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('pack', 'Pack', 70);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('box', 'Box', 80);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('bundle', 'Bundle', 90);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('bag', 'Bag', 100);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('bottle', 'Bottle', 110);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('can', 'Can', 120);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('roll', 'Roll', 130);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('meter', 'Meter', 140);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('foot', 'Foot', 150);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('sqft', 'Square Foot', 160);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('day', 'Day', 170);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('week', 'Week', 180);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('month', 'Month', 190);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('year', 'Year', 200);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('bill', 'Bill / Invoice', 210);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('service', 'Service', 220);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('visit', 'Visit', 230);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('load', 'Load / Trip', 240);
INSERT OR IGNORE INTO ledger_uoms (code, label, sort_order) VALUES ('set', 'Set', 250);

-- ─── PRODUCTS ───
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Chicken Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Chicken Cutlet Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Mutton Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Brain Purchase (Sajid)', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Milk Purchase', 'ltr', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Milk Powder Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Butter Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Ghee Purchase', 'ltr', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Buns Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Rumali Roti', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Tea Powder Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Oil Purchase', 'ltr', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Onion Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Vegetables / Fruits / Dairy / Staff Food', 'bag', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Groceries / Oils / Masalas — Shariff Store', 'bag', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Groceries — Other Store', 'bag', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Biscuits — Galaxy Bakery', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Biscuits — Osmania (Loose)', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Biscuits — Karachi Bakery', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Biscuits — Nilofer', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Samosa Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Cool Drinks Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Soft Drinks', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Horlicks / Boost / Coffee', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Shawarma Raw Materials', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Haleem Raw Materials', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Charcoal Purchase', 'kg', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Cooking Wood', 'bundle', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (1, 'Raw Material Purchase (uncategorised)', 'bag', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Aadil', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Ajim', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Amin', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Ansu', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Ashif', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Bhasheer', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Cleaning Boys', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Dananjay', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Deeraj Kumar', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Fahim', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Faizal Ali', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Faizan', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Farooq', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Farzaib', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Hamza', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Hardev Singh', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Jafar / Jahangeer / Aroop', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Kismat', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Makbul', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — MD Akthar', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Mujib', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Mumtaz', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Nafeez (Supervisor)', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Nasim', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Naveen Kumar', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Nihaf (Abdul Khader)', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Noim', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Noor', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Osim Akram SK', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Ranjan', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Riyaz', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Shabir', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Sheru Khan', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Somesh', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Tabarak', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Tanveer Ahmed', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Velu', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Wasim', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Yashwant Jodha', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Salary — Zoya', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Eid Bonus', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Staff Bonus', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (2, 'Payroll Commission', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (3, 'Outlet Rent — NCH', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (3, 'Outlet Rent — HE', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (3, 'HQ / Office Rent', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Electricity Bill', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Gas Cylinders', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Gas Regulator Tap', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Water Bottles', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Water Cans', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Water Pipes', 'foot', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Internet — ACT Fibre', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'Internet — Jio Wifi', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'LAN / Cabling Labour', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (4, 'BWSSB Water Bill', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Disposable Materials', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Cleaning Materials', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Dust Bins', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tissue Paper Bundle', 'bundle', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tissue Paper Holders', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Storage Cans', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Stationery Purchase', 'pack', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Office Staff Food & Snacks', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Staff Welfare / Medicine', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Staff Welfare — Tea Master', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Floor Mats', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Floor Sleeping Mat for Staff', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tea Cloth', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tea Cups & Saucer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tea Equipment & Items', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Tea / Coffee Tokens', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Cutting Board', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Haleem Mat (Red Colour)', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Glass & Plates', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Sulemani Glass', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Parcel Box', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Thermal Printer Rolls', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Knife Sharpener', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'No Smoking Boards', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Table Number Signs', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Coin Box', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Wiper & Tap', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Spanner Set', 'set', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Newspaper', 'bundle', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Iftar Expenses', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Misc. Petty Cash', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Refund — Customer', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Double-side Tape', 'roll', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (5, 'Uniform Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Deep Cleaning', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Welder Labour', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Electrician Labour', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Packing Machine', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Electrical Adapter', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, '6-to-16 Adapter', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Power Adapter', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Pest Control', 'visit', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Plumbing', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Fabrication / Welding Work', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Equipment Repair', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Malar Expenses', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Shaheen Expenses', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'Garbage / Waste Disposal', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (6, 'BBMP Commission', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Business Promotion', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Printing (Flyers / Cards)', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'QR Codes Printing', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Swiggy / Zomato Onboarding', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Meta / Facebook Ads', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Google Ads', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (7, 'Influencer Collab', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Claude AI Subscription', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Cloudflare Subscription', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Odoo Hosting / Subscription', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Federal Bank Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'HDFC Bank Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Naveen Bank Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Razorpay Gateway Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Paytm Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (8, 'Generic Bank Charges', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (9, 'Sparksol MCA Filings', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (9, 'FSSAI / Food Licence', 'year', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (9, 'GST Filing', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (9, 'CA / Audit', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (9, 'Trade Licence', 'year', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (10, 'Police Payment', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (10, 'Beat Payment', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (10, 'Cheta Payment', 'bill', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'All-in-One Android PC', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Android KDS (Imin)', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Ethernet Connector', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Keyboard & Accessories', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Screen Guard for KDS', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'VGA Cable', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Wifi Adapter', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Wifi Dongle', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Wifi Extender', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Acer Monitor', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'AMS Monitor', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Windows Mini PC', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Chicken Trail (Equipment)', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Coal Bhatti', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Electric Stove', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Mixer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Soan Bhatti', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'SS Table', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Stove Frame', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Tandoori Stick & Cigdi', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Woven Purchase', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Barcode Scanner', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Epson M30iii Printer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Sreyans Printer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Thermal Barcode Printer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Air Conditioner', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Amazon Fire Stick', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'CAMS Biometric System', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'CCTV Camera', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Ceiling Mount', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Door Purchase & Fitting', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Extra Pipes for KDS', 'meter', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Godraj Locker', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Parking Stand (Iron)', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'PC Mount', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Weight Machine', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, '6-to-16 Adapter', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Coin Box', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Tea Cups & Saucer', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (11, 'Tea Equipment & Items', 'pcs', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (12, 'Rapido / Porter / Transport', 'service', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (12, 'Petrol & Diesel', 'ltr', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (12, 'Auto Fare', 'visit', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (12, 'Cab / Uber', 'visit', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (13, 'Juhaina Haneef — Withdrawal', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (13, 'Juvairia Haneef — Withdrawal', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (13, 'KM Haneef — Withdrawal', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (13, 'Nihaf — Personal Expenses', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (13, 'Tanveer — Paid Out', 'month', 'seed');
INSERT OR IGNORE INTO ledger_products (category_id, name, default_uom, created_by) VALUES (14, 'Uncategorised / Review', 'bill', 'seed');

-- ─── VENDORS ───
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Shariff Departmental Store', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('M N Chicken', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Galaxy Bakery', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Osmania Bakery', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Nilofer Bakery', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Karachi Bakery', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Sajid (Brain Supplier)', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('BESCOM', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('BWSSB', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('HDFC Bank', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Federal Bank', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Razorpay', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Paytm', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Cloudflare', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Anthropic (Claude)', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Sparksol', NULL);
INSERT OR IGNORE INTO ledger_vendors (name, phone) VALUES ('Prabhu Buffalo Milk', NULL);

-- seeded: 14 categories · 25 UOMs · 204 products · 17 vendors
