#!/usr/bin/env python3
"""Generate ops-db/seed.sql + ops-db/migrate_18june.sql from live hn-hiring dumps.
Routes each 18-June PO line to a vendor via item/alias data (no guessing), then
groups one-vendor=one-card. Prints the routing so it can be verified before load."""
import json, re, sys

def load(p): return json.load(open(p))[0]['results']
items   = load('/tmp/items.json')
aliases = load('/tmp/aliases.json')
vendors = load('/tmp/vendors.json')
staff   = load('/tmp/staff.json')
po18    = load('/tmp/po18.json')

def q(v):
    if v is None: return 'NULL'
    return "'" + str(v).replace("'", "''") + "'"
def n(v):
    return 'NULL' if v is None or v=='' else str(v)

OUTLET = {'HE':'he-shivajinagar','NCH':'nch-shivajinagar'}

# ---- resolver: deterministic, safe. exact (paren-stripped) -> token-Jaccard.
# Reused as the real app's decode->route engine. Never an arbitrary substring.
by_code = {it['item_code']: it for it in items}
_STOP = {'kg','g','gm','gms','gram','grams','l','ltr','litre','ml','pc','pcs','piece','pieces',
 'packet','pack','pkt','bundle','case','crate','box','bag','of','the','and','a'}
def norm(s):
    s=(s or '').strip().lower()
    s=re.sub(r'\(.*?\)','',s)            # drop parenthetical qualifiers
    return re.sub(r'\s+',' ',s).strip()
def toks(s):
    out=set()
    for w in re.split(r'[^a-z0-9]+', norm(s)):
        if len(w)<2 or w in _STOP: continue
        if len(w)>3 and w.endswith('s'): w=w[:-1]   # crude singularize
        out.add(w)
    return out
exact={}                                  # normalized label/alias -> code
cand=[]                                   # (code, tokenset)
for it in items:
    exact.setdefault(norm(it['label']), it['item_code'])
    cand.append((it['item_code'], toks(it['label'])))
for a in aliases:
    exact.setdefault(norm(a['alias']), a['item_code'])
    cand.append((a['item_code'], toks(a['alias'])))

def route(label, flagged=False):
    key=norm(label)
    if key in exact: return (exact[key], by_code[exact[key]])
    if flagged: return (None,None)        # never fuzzy a decode-flagged-unknown line
    q=toks(label)
    if not q: return (None,None)
    best=None; best_s=0.0
    for code,ts in cand:
        if not ts: continue
        inter=q & ts
        if not inter or not any(len(w)>=3 for w in inter): continue
        s=len(inter)/len(q|ts)
        if s>best_s or (s==best_s and best and len(code)<len(best)):
            best_s=s; best=code
    if best and best_s>=0.5: return (best, by_code[best])
    return (None,None)

def parse_qty(qstr):
    m = re.match(r'\s*([0-9]+(?:\.[0-9]+)?)', str(qstr or ''))
    return float(m.group(1)) if m else None

# unit normalization — only price a line when its order-unit matches the item's
# price-unit (else gm-qty x per-kg-price inflates the total). Amount is a soft
# pre-fill; the real bill is confirmed at receive/pay.
_UN = {'kg':'kg','kilo':'kg','kgs':'kg','g':'g','gm':'g','gms':'g','gram':'g','grams':'g',
 'l':'l','ltr':'l','litre':'l','liter':'l','liters':'l','litres':'l','ml':'ml',
 'pc':'pc','pcs':'pc','piece':'pc','pieces':'pc','no':'pc','nos':'pc','pkt':'packet',
 'packet':'packet','packets':'packet','pack':'packet','bundle':'bundle','bundles':'bundle',
 'case':'case','crate':'crate','cylinder':'cylinder','bag':'bag','box':'box','bunch':'bunch',
 'bird':'bird','birds':'bird'}
def nu(u): return _UN.get((u or '').strip().lower(), (u or '').strip().lower())

# ============================ seed.sql =====================================
S = []
S.append("-- AUTO-GENERATED by build_seed.py. Seeds outlets, roles, staff, vendors, items.")
S.append("DELETE FROM outlets; DELETE FROM roles; DELETE FROM staff; DELETE FROM vendors; DELETE FROM items; DELETE FROM item_aliases;")

# outlets
S.append("INSERT INTO outlets (outlet_id,brand,name,city,odoo_instance,odoo_company_id,settlement_model) VALUES")
S.append("  ('he-shivajinagar','HE','Hamza Express','Bangalore','test.hamzahotel.com',2,'owes_ledger'),")
S.append("  ('nch-shivajinagar','NCH','Nawabi Chai House','Bangalore','ops.hamzahotel.com',10,'discrete');")

# roles
ROLES = [
 ('owner','Owner / MD', ["sauda.place","sauda.receive","sauda.raise","sauda.pay","anbar.receive","anbar.count","anbar.audit","takht.settle","takht.take","takht.account","takht.fix","admin.assign"],100),
 ('manager','Manager', ["sauda.place","sauda.receive","sauda.raise","anbar.receive","anbar.count","anbar.audit","takht.settle","takht.take","takht.account","takht.fix"],80),
 ('buyer','Buyer', ["sauda.place","sauda.receive","sauda.raise"],50),
 ('cashier','Cashier', ["takht.take","takht.account","takht.fix"],40),
 ('runner','Runner / Captain', ["takht.settle"],30),
 ('kitchen','Kitchen / Cook', ["anbar.receive","anbar.count"],20),
 ('counter','Counter', ["anbar.receive","anbar.count"],20),
 ('none','No app access', [],0),
]
for rk,lbl,caps,rank in ROLES:
    S.append(f"INSERT INTO roles (role_key,label,capabilities,rank) VALUES ({q(rk)},{q(lbl)},{q(json.dumps(caps))},{rank});")

# staff role mapping
def role_for(job):
    j=(job or '').strip().lower()
    if 'managing director' in j: return 'owner'
    if 'general manager' in j: return 'manager'
    if 'office executive' in j: return 'buyer'
    if 'cashier' in j: return 'cashier'
    if 'runner' in j or 'captain' in j: return 'runner'
    if 'waiter' in j or 'steward' in j: return 'counter'
    if any(w in j for w in ['chef','cook','tandoor','porotta','helper','chai master','assistant']): return 'kitchen'
    return 'none'
for s in staff:
    bl=(s.get('brand_label') or '').upper()
    outs = ['he-shivajinagar','nch-shivajinagar'] if bl=='HQ' else ([OUTLET[bl]] if bl in OUTLET else [])
    nm = s.get('known_as') or s.get('name')
    rk = role_for(s.get('job_name'))
    S.append(f"INSERT INTO staff (staff_pin,name,role_key,outlet_ids,brand,job_name) VALUES "
             f"({q(str(s['staff_pin']))},{q(nm)},{q(rk)},{q(json.dumps(outs))},{q(bl)},{q(s.get('job_name') or '')});")

# vendors  (brand normalize: sauda_vendor.brand was 'both'|'HE'|'NCH')
for v in vendors:
    S.append("INSERT INTO vendors (vendor_key,name,brand,category,fulfilment,pay_behaviour,phone,vpa_json,aliases_json) VALUES "
        f"({q(v['vendor_key'])},{q(v['name'])},{q(v.get('brand') or 'both')},{q(v.get('cat') or '')},"
        f"{q(v.get('fulfilment') or 'deliver')},{q(v.get('pay') or 'per')},{q((v.get('phone') or '').strip())},"
        f"{q(v.get('vpa_json') or '[]')},{q(v.get('aliases_json') or '[]')});")
# sentinel vendor for unrouted lines (productive failure surface)
S.append("INSERT INTO vendors (vendor_key,name,brand,category,fulfilment,pay_behaviour) VALUES "
         "('_unrouted','⚠ Needs vendor','both','Unrouted','collect','per');")

# items + aliases
for it in items:
    S.append("INSERT INTO items (item_code,label,unit,price_paise,price_mode,default_vendor,category,brand) VALUES "
        f"({q(it['item_code'])},{q(it['label'])},{q(it.get('unit') or '')},{n(it.get('price_paise') or 0)},"
        f"{q(it.get('price_mode') or 'fixed')},{q(it.get('default_vendor') or '')},{q(it.get('category') or '')},{q(it.get('brand') or '')});")
for a in aliases:
    S.append(f"INSERT OR IGNORE INTO item_aliases (alias,item_code) VALUES ({q(a['alias'].strip().lower())},{q(a['item_code'])});")

open('ops-db/seed.sql','w').write("\n".join(S)+"\n")

# ====================== migrate_18june.sql + routing report =================
M = ["-- AUTO-GENERATED: 18-June sauda_po -> one-vendor=one-card purchase_orders",
     "DELETE FROM purchase_order_lines WHERE order_id IN (SELECT id FROM purchase_orders WHERE for_date='2026-06-18');",
     "DELETE FROM purchase_orders WHERE for_date='2026-06-18';"]
cards = {}   # (outlet, vendor) -> list of line dicts
report = []
for po in po18:
    brand = po['brand']; outlet = OUTLET[brand]
    for ln in json.loads(po['items_json']):
        label = ln.get('item') or ln.get('raw')
        decode_flag = ln.get('flag') or ''
        code, it = route(label, flagged=('unknown' in decode_flag.lower()))
        vk = (it['default_vendor'] if it and it.get('default_vendor') else '') or '_unrouted'
        qty = parse_qty(ln.get('qty'))
        unit = ln.get('unit') or (it.get('unit') if it else '')
        price = (it.get('price_paise') if it and (it.get('price_mode')!='live') else 0) or 0
        unit_ok = bool(it) and price and nu(unit) == nu(it.get('unit'))
        amt = int(round(qty*price)) if (qty is not None and unit_ok) else 0
        flag = ln.get('flag') or ('' if code else 'unmapped item — confirm vendor')
        if price and qty is not None and not unit_ok and not flag:
            flag = f"price is per {it.get('unit') or '?'} — confirm at bill"
        cards.setdefault((outlet,vk),[]).append(dict(code=code or '',label=label,qty=qty,unit=unit,
            price=(price if unit_ok else 0),amt=amt,flag=flag,raw=ln.get('raw') or ''))
        report.append((outlet,vk,label,qty,unit,code or '-',(price if unit_ok else 0),amt,flag[:34]))

# emit cards
for (outlet,vk),lines in cards.items():
    exp = sum(l['amt'] for l in lines)
    M.append("INSERT INTO purchase_orders (outlet_id,vendor_key,for_date,status,expected_amount_paise,source,ordered_at,ordered_by) "
        f"VALUES ({q(outlet)},{q(vk)},'2026-06-18','ORDERED',{exp},'migration-18jun','2026-06-18T08:00:00+05:30','Zoya Ahmed');")
    M.append(f"INSERT INTO vendor_ledger (outlet_id,vendor_key,delta_paise,kind,note) VALUES ({q(outlet)},{q(vk)},{exp},'order','18-Jun migration');")
    for l in lines:
        M.append("INSERT INTO purchase_order_lines (order_id,item_code,item_label,qty_ordered,uom,unit_cost_paise,line_amount_paise,flag,raw) "
            f"VALUES ((SELECT id FROM purchase_orders WHERE outlet_id={q(outlet)} AND vendor_key={q(vk)} AND for_date='2026-06-18'),"
            f"{q(l['code'])},{q(l['label'])},{n(l['qty'])},{q(l['unit'])},{l['price']},{l['amt']},{q(l['flag'])},{q(l['raw'])});")
open('ops-db/migrate_18june.sql','w').write("\n".join(M)+"\n")

# ----- print report grouped by card -----
print("=== 18-JUNE ROUTING -> ONE VENDOR ONE CARD ===")
vname = {v['vendor_key']: v['name'] for v in vendors}; vname['_unrouted']='⚠ Needs vendor'
from collections import defaultdict
g=defaultdict(list)
for outlet,vk,label,qty,unit,code,price,amt,flag in report: g[(outlet,vk)].append((label,qty,unit,code,price,amt,flag))
tot_lines=0; unrouted=0
for (outlet,vk),ls in sorted(g.items()):
    exp=sum(a for *_,a,_ in ls)
    print(f"\n[{outlet}]  CARD: {vname.get(vk,vk)}  ({vk})   Rs {exp/100:,.0f}  · {len(ls)} lines")
    for label,qty,unit,code,price,amt,flag in ls:
        tot_lines+=1
        if vk=='_unrouted': unrouted+=1
        pr = f"@{price/100:.0f}" if price else "@—"
        print(f"    - {label:28} {str(qty or ''):>5} {unit:8} {pr:6} = {amt/100:>7.0f}  [{code}] {('!! '+flag) if flag else ''}")
print(f"\nTOTAL: {len(g)} vendor-cards, {tot_lines} lines, {unrouted} unrouted")
