name: Takht
options:
  bundleIdPrefix: in.hnhotels
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    WATCHOS_DEPLOYMENT_TARGET: 10.0
targets:
  Takht:
    type: application
    platform: iOS
    sources:
      - path: Sources/Takht
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: in.hnhotels.takht
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Takht
        INFOPLIST_KEY_CFBundleName: Takht
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: ["UIInterfaceOrientationPortrait"]
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: in.hnhotels.takht.watchkitapp
    info:
      path: Sources/Takht/Info.plist
    entitlements:
      path: Sources/Takht/Takht.entitlements
    dependencies:
      - target: TakhtWatch App

  TakhtWatch App:
    type: application.watchapp2
    platform: watchOS
    sources:
      - path: Sources/TakhtWatch
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: in.hnhotels.takht.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Takht Watch
        INFOPLIST_KEY_CFBundleName: TakhtWatch
        INFOPLIST_KEY_WKWatchOnly: YES
    info:
      path: Sources/TakhtWatch/Info.plist
    entitlements:
      path: Sources/TakhtWatch/TakhtWatch.entitlements

  TakhtWatch Extension:
    type: watchkit2-extension
    platform: watchOS
    sources:
      - path: Sources/TakhtWatchExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: in.hnhotels.takht.watchkitextension
        INFOPLIST_KEY_CFBundleDisplayName: TakhtWatchExtension
        WK_APP_BUNDLE_IDENTIFIER: in.hnhotels.takht.watchkitapp
    info:
      path: Sources/TakhtWatchExtension/Info.plist
    entitlements:
      path: Sources/TakhtWatchExtension/TakhtWatchExtension.entitlements
    dependencies:
      - target: TakhtWatch App

